[package]
name = "mini-base"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
sqlx = { version = "0.6.3", features = [  "runtime-async-std-native-tls", "sqlite", "mysql", "postgres" ] }
async-std = { version = "1", features = [ "attributes" ] }
pbkdf2 = "0.12.1"
axum = "0.6.12"
cursive = { git = "https://github.com/gyscos/cursive", default-features=false, features=["crossterm-backend"] }
nom = "7.1.3"
futures = "0.3.28"
