[package]
name = "mini-base"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6.3", features = [  "runtime-async-std-native-tls", "sqlite", "mysql", "postgres", "time", "json" ] }
async-std = { version = "1", features = [ "attributes" ] }
pbkdf2 = "0.12.1"
axum = "0.6.12"
cursive = { git = "https://github.com/gyscos/cursive" }
nom = "7.1.3"
futures = "0.3.28"
serde_json = "1.0.96"
serde = "1.0.160"
tokio = { version="1.27.0", features= [ "full" ] }
axum-server = "0.4.7"
